apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auth
type: Opaque
data:
  DATABASE_URL: "Tm9uZQ=="
  MASTER_KEY: "Tm9uZQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: flag
type: Opaque
data:
  DATABASE_URL: "Tm9uZQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: "Tm9uZQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: evaluation
type: Opaque
data:
  SERVICE_API_KEY: "Tm9uZQ=="
  REDIS_URL: "Tm9uZQ=="
  AWS_SQS_URL: "Tm9uZQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: analytics
type: Opaque
data:
  AWS_SQS_URL: "Tm9uZQ=="

